### ISSUE TITLE
toc-ui目前不支持npm引入？

### ISSUE THREAD

**Issue by enjoyWeb** [dishait/tob-ui#4]
tob-ui目前不支持npm引入？

**Comment by markthree** [comment]
不支持，只支持插件市场引入

**Comment by enjoyWeb** [comment]
> 不支持，只支持插件市场引入

有打算支持麽，或者说出于什么考虑不支持

**Comment by markthree** [comment]
因为我现在在做其他的工作，所以短时间是不考虑支持的。

考虑的话，应该算是偏好吧。当然我喜欢包管理器的项目管理，但其实大多数同学喜欢一键安装 😂
